apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: appbuilder
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "nodejs-instrumentation"
      labels:
        app: api
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: prod-private
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: api
      containers:
      - name: api
        image: sathish8329/appbuilderback:6503
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3


---
apiVersion: v1
kind: Service
metadata:
  name: appbuilder-api-service
  namespace: appbuilder
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
